# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_card.ipynb.

# %% auto 0
__all__ = ['Card']

# %% ../00_card.ipynb 2
from fastcore.all import *
import random

# %% ../00_card.ipynb 3
class Card:
    "Represents a standard playing card."

    suit_names = ["Clubs", "Diamonds", "Hearts", "Spades"]
    rank_names = [None, "Ace"] + [str(x) for x in range(2,11)]  + ["Jack", "Queen", "King"]

    def __init__(self, suit=0, rank=2):
        self.suit, self.rank = suit, rank
        self.suit_nm = Card.suit_names[self.suit]
        self.rank_nm = Card.rank_names[self.rank]

    def __str__(self):
        "Returns a human-readable string representation."
        return f'{self.rank_nm} of {self.suit_nm}'

    def __eq__(self, other) -> bool:
        "Checks whether self and other have the same rank and suit."
        return self.suit == other.suit and self.rank == other.rank

    def __lt__(self, other) -> bool:
        "Compares this card to `other`, first by suit, then rank."
        return (self.suit, self.rank) < (other.suit, other.rank)
    
    def __repr__(self): return self.__str__()
